import { test, expect } from '@playwright/test'

test('real course study, evidence, conversation, quiz and sprint', async ({page})=>{
  const errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Let’s make it click.'})).toBeVisible()
  await page.screenshot({path:'../data/ui/workspace.png',fullPage:true})
  await page.getByLabel('Your course question').fill('What is an array?')
  await page.getByRole('button',{name:'Find evidence',exact:true}).click()
  await expect(page.locator('.answer-status').last()).toHaveText(/answered/i,{timeout:90000})
  await expect(page.locator('.claim').last()).toContainText('collection')
  await page.locator('.claim .citation').first().click()
  await expect(page.locator('.source-meta')).toContainText('Handwritten note')
  await expect(page.locator('.preview')).toBeVisible()
  await expect(page.locator('.excerpt')).toContainText('Array')
  await expect(page.locator('.source-footer')).toContainText('ai visual transcription')
  await page.screenshot({path:'../data/ui/handwriting-evidence.png',fullPage:true})
  await page.getByRole('button',{name:'Explain simply',exact:true}).click()
  await expect(page.locator('.answer-panel')).toHaveCount(2,{timeout:90000})
  await expect(page.locator('.answer-status').last()).toHaveText(/answered/i)
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByRole('status').last()).toContainText('saved')
  await page.getByRole('button',{name:'Quiz me',exact:true}).click()
  await page.getByLabel('Quiz answer').fill('deliberately incorrect')
  await page.getByRole('button',{name:'Check answer',exact:true}).click()
  await expect(page.locator('.grade')).toContainText('needs another look')
  await page.getByRole('button',{name:'See your Exam Sprint'}).click()
  await expect(page.locator('.topic-state.weak')).toBeVisible()
  await expect(page.locator('.saved-card')).toHaveCount(1)
  await page.screenshot({path:'../data/ui/exam-sprint.png',fullPage:true})
  await page.getByRole('button',{name:'Study workspace',exact:true}).click()
  await page.getByLabel('Your course question').fill('Compare array and class')
  await page.getByRole('button',{name:'Find evidence',exact:true}).click()
  await expect(page.locator('.answer-panel')).toHaveCount(3,{timeout:90000})
  await expect(page.locator('.answer-panel').last().locator('.claim')).toHaveCount(2)
  const names=await page.locator('.answer-panel').last().locator('.citation').allTextContents()
  expect(new Set(names).size).toBeGreaterThanOrEqual(2)
  await page.getByLabel('Your course question').fill('Explain array and garbage collection')
  await page.getByRole('button',{name:'Find evidence',exact:true}).click()
  await expect(page.locator('.answer-status').last()).toHaveText(/partially answered/i,{timeout:90000})
  await page.getByLabel('Your course question').fill('What is quantum control?')
  await page.getByRole('button',{name:'Find evidence',exact:true}).click()
  await expect(page.locator('.answer-status').last()).toHaveText(/not covered/i,{timeout:90000})
  await page.reload()
  await expect(page.locator('.answer-panel')).toHaveCount(5)
  expect(errors).toEqual([])
})

test('mobile layout and materials remain usable',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await expect(page.getByLabel('Your course question')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Course materials',exact:true}).click()
  await expect(page.locator('.material-card').first()).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'../data/ui/materials-mobile.png',fullPage:true})
})
