import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowUpRight, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, FileText, FolderOpen, GraduationCap, Layers, LoaderCircle, Plus, Search, ShieldCheck, Sparkles, Target, Upload, Bookmark, X, RotateCcw } from 'lucide-react'
import { api } from './api'
import GroundedClaims from './GroundedClaims'
import type { Answer, Document, Message, Source, Sprint } from './api'

const examples = ['What is a class?', 'What is an array?', 'Explain encapsulation', 'Compare arrays and ArrayList']
const label = (value:string) => value.toLowerCase().replaceAll('_',' ')
function Evidence({source,onClose}:{source:Source|null;onClose:()=>void}){
  const [failed,setFailed]=useState(false)
  useEffect(()=>setFailed(false),[source?.chunk_id])
  return <aside className="evidence panel"><div className="panel-heading"><div><span className="eyebrow">VERIFY AS YOU STUDY</span><h2><Layers size={18}/> Source evidence</h2></div>{source&&<button className="icon-button" aria-label="Close evidence" onClick={onClose}><X size={18}/></button>}</div>{source?<>
    <div className="source-meta"><span className="type-tag">{source.source_type==='handwritten'?'Handwritten note':label(source.source_type)}</span><h3>{source.document_name.split('/').pop()}</h3><p>{source.location} <span>·</span> {label(source.extraction_quality)} extraction quality</p></div>
    {['pdf','pptx','handwritten'].includes(source.source_type)&&!failed?<a href={source.preview_url} target="_blank" rel="noreferrer" className="preview-link" title="Open full-size evidence"><img className="preview" src={source.preview_url} onError={()=>setFailed(true)} alt={`Original evidence: ${source.document_name}, ${source.location}`}/><span>Open full-size preview <ArrowUpRight size={14}/></span></a>:<div className="preview-placeholder"><FileText size={30}/><p>Read the source excerpt below or open the original file.</p></div>}
    <div className="excerpt"><span className="eyebrow">EXTRACTED REPRESENTATION</span><p>{source.text}</p></div><div className="source-footer"><p>Extraction: {label(source.extraction_method)}. Check the original when wording or symbols are uncertain.</p><a className="text-link" href={source.original_url} target="_blank" rel="noreferrer">Open original file <ArrowUpRight size={15}/></a></div>
  </>:<div className="evidence-empty"><div className="empty-art"><FileText size={42}/><span><ShieldCheck size={22}/></span></div><h3>Every answer has a paper trail.</h3><p>Select a citation to inspect its exact page, slide, section, or handwritten original.</p><div className="evidence-principles"><p><Check size={15}/> Precise source locations</p><p><Check size={15}/> Original evidence, one click away</p><p><Check size={15}/> Uncertain text stays uncertain</p></div></div>}</aside>
}

function App(){
  const [page,setPage]=useState<'study'|'materials'|'sprint'>('study')
  const [docs,setDocs]=useState<Document[]>([])
  const [session,setSession]=useState(()=>localStorage.getItem('exampilot-session')||'')
  const [messages,setMessages]=useState<Message[]>([])
  const [question,setQuestion]=useState('')
  const [document,setDocument]=useState('')
  const [sourceType,setSourceType]=useState('')
  const [selected,setSelected]=useState<Source|null>(null)
  const [busy,setBusy]=useState('')
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  const [sprint,setSprint]=useState<Sprint|null>(null)
  const [quiz,setQuiz]=useState<{id:string;question:string;topic:string}|null>(null)
  const [quizInput,setQuizInput]=useState('')
  const [grade,setGrade]=useState<{correct:boolean;expected:string;evidence:string}|null>(null)
  const [health,setHealth]=useState<{provider:string;corpus:string;retrieval:string}|null>(null)
  const latest=messages.at(-1)?.answer
  const units=docs.reduce((n,d)=>n+d.units,0)

  useEffect(()=>{Promise.all([api<Document[]>('/documents'),api<{provider:string;corpus:string;retrieval:string}>('/health')]).then(([d,h])=>{setDocs(d);setHealth(h)}).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(session){localStorage.setItem('exampilot-session',session);api<{messages:Message[]}>('/session/'+session).then(r=>setMessages(r.messages)).catch(e=>setError(e.message))}},[session])
  useEffect(()=>{if(page==='sprint'&&session)api<Sprint>('/exam-sprint/'+session).then(setSprint).catch(e=>setError(e.message))},[page,session])

  async function ask(text=question,action='ask'){
    if(!text.trim()||busy)return
    setBusy('Finding course evidence');setError('');setNotice('');setQuiz(null);setGrade(null)
    try{const answer=await api<Answer>(action==='ask'?'/ask':'/study/action',{question:text,session_id:session||null,document_id:document||null,source_type:sourceType||null,action});
      if(!session){localStorage.setItem('exampilot-session',answer.session_id);setSession(answer.session_id)}
      setMessages(m=>[...m,{question:text,answer,created:new Date().toISOString()}]);setSelected(answer.sources[0]||null);setQuestion('');setPage('study')
    }catch(e){setError((e as Error).message)}finally{setBusy('')}
  }
  async function newSession(){if(busy)return;try{const data=await api<{session_id:string}>('/session',{});setSession(data.session_id);setMessages([]);setSelected(null);setQuiz(null);setGrade(null);setNotice('A fresh study session is ready.');setPage('study')}catch(e){setError((e as Error).message)}}
  async function ingest(){setBusy('Reading local course files');setError('');try{const r=await api<{errors:{file:string;error:string}[]}>('/ingest',{});setDocs(await api<Document[]>('/documents'));setNotice(r.errors.length?`${r.errors.length} source(s) need attention: ${r.errors.map(e=>e.file+': '+e.error).join('; ')}`:'Local materials indexed. Your originals are preserved.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  async function upload(file:File){setBusy('Uploading and reading source');setError('');try{const form=new FormData();form.append('file',file);const response=await fetch('/api/upload',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Upload failed');setDocs(await api<Document[]>('/documents'));setNotice(result.errors?.length?'File saved, but extraction needs attention. Check your source and re-index.':'Source added to your local course material.')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  async function makeQuiz(){setBusy('Preparing an evidence-based quiz');try{setQuiz(await api('/quiz/generate',{session_id:session}));setGrade(null);setQuizInput('')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  async function gradeQuiz(e:FormEvent){e.preventDefault();setBusy('Checking your recall');try{setGrade(await api('/quiz/answer',{session_id:session,quiz_id:quiz?.id,answer:quizInput}))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  async function save(){try{await api('/revision/save',{session_id:session});setNotice('Evidence saved to Exam Sprint.')}catch(e){setError((e as Error).message)}}
  function citation(id:string,answer:Answer){const source=answer.sources.find(s=>s.chunk_id===id);return <button key={id} className="citation" onClick={()=>source&&setSelected(source)} title={source?.document_name}><FileText size={12}/>{source?.document_name.split('/').pop()?.slice(0,32)||'Source'} · {source?.location}<ArrowUpRight size={12}/></button>}

  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('study')}}><div className="brand-icon"><GraduationCap size={24}/></div><span>ExamPilot<small>YOUR MATERIAL. YOUR MOMENT.</small></span></a><div className="sidebar-section">YOUR STUDY SPACE</div><nav>{([{id:'study',icon:BookOpen,name:'Study workspace'},{id:'materials',icon:FolderOpen,name:'Course materials'},{id:'sprint',icon:Target,name:'Exam Sprint'}] as const).map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>setPage(n.id)}><n.icon size={18}/>{n.name}{page===n.id&&<ChevronRight size={16}/>}</button>)}</nav><button className="new-session" onClick={newSession} disabled={!!busy}><Plus size={16}/> New study session</button><div className="sidebar-bottom"><ShieldCheck size={24}/><h3>Grounded Study Mode</h3><p>Your course material is the authority. Missing evidence stays missing.</p><div className="status-dot">Local workspace</div></div><div className="sidebar-footer">Made for the night before.</div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb">My workspace <ChevronRight size={14}/> <strong>{page==='study'?'Study with evidence':page==='materials'?'Course materials':'Exam Sprint'}</strong></div><span className="grounded-badge"><ShieldCheck size={14}/> Evidence first</span></header><main>
    <div className="page-title"><div><span className="eyebrow">{page==='study'?'LESS GUESSING. MORE UNDERSTANDING.':page==='materials'?'YOUR SOURCE OF TRUTH':'MAKE YOUR NEXT STUDY MINUTE COUNT'}</span><h1>{page==='study'?'Let’s make it click.':page==='materials'?'One place for your course.':'Focus where it matters.'}</h1><p>{page==='study'?'Ask, understand, and trace every answer back to your material.':page==='materials'?'Bring your lectures, slides, and handwritten notes together.':'A revision plan shaped by what you have actually studied.'}</p></div><div className="course-chip"><div className="course-icon"><BookOpen size={20}/></div><span>{health?.corpus==='demo'?'Synthetic demo corpus':'My local course material'}<small>{docs.length} sources · {units} pages / slides / sections</small></span></div></div>
    {error&&<div className="alert error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="alert" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}{busy&&<div className="busy" role="status"><LoaderCircle size={16} className="spin"/>{busy}… {busy.includes('evidence')&&'The first semantic search can take a moment.'}</div>}
    {page==='study'&&<div className="workspace-grid"><section className="study-column"><div className="question-panel panel"><div className="panel-heading"><h2><Sparkles size={19}/> What are we working on?</h2><span className="small-muted">{latest?'Keep the conversation going':'Start with a course question'}</span></div><form onSubmit={e=>{e.preventDefault();void ask()}}><label className="sr-only" htmlFor="question">Your course question</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question, compare two concepts, or untangle a tricky topic…" maxLength={2000} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void ask()}}}/><div className="question-toolbar"><div className="filters"><label><FileText size={14}/><select aria-label="Filter by document" value={document} onChange={e=>setDocument(e.target.value)}><option value="">All sources</option>{docs.map(d=><option key={d.id} value={d.id}>{d.name.split('/').pop()}</option>)}</select></label><select aria-label="Filter by source type" value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="">Any format</option><option value="pdf">PDF</option><option value="pptx">Slides</option><option value="handwritten">Handwriting</option><option value="markdown">Markdown</option><option value="text">Text</option></select></div><button className="primary" disabled={!!busy||!question.trim()} type="submit">Find evidence <ArrowRight size={16}/></button></div></form><div className="suggestions"><span>TRY ASKING</span>{examples.map(q=><button disabled={!!busy} key={q} onClick={()=>void ask(q)}>{q}<ArrowUpRight size={12}/></button>)}</div></div>
    {!messages.length?<div className="start-guide"><div className="guide-number">01</div><div><h3>Start with what you need to understand.</h3><p>ExamPilot searches your sources, checks which parts are supported, and keeps the evidence beside the answer.</p></div><div className="guide-points"><span><Search size={17}/> Ask a real question</span><span><Layers size={17}/> Check the evidence</span><span><Target size={17}/> Test your recall</span></div></div>:<div className="answers">{messages.map((message,i)=><article className="answer-panel panel" key={i}><div className="answer-question"><span className="question-number">{String(i+1).padStart(2,'0')}</span><h2>{message.question}</h2></div><div className="answer-body"><span className={'answer-status '+message.answer.status.toLowerCase()}>{message.answer.status==='ANSWERED'?<ShieldCheck size={14}/>:<CircleHelp size={14}/>} {label(message.answer.status)}</span><GroundedClaims answer={message.answer} citation={id=>citation(id,message.answer)}/><div className="coverage"><h3>Evidence completeness <span>{message.answer.coverage.filter(n=>n.supported).length}/{message.answer.coverage.length} requested parts supported</span></h3>{message.answer.coverage.map((need,n)=><div className="coverage-row" key={n}><span>{need.need}</span><strong className={need.supported?'supported':'missing'}>{need.supported?<Check size={13}/>:<CircleHelp size={13}/>} {need.supported?'Supported':'Not found'}</strong></div>)}</div>{!message.answer.claims.length&&message.answer.sources.length>0&&<div className="related"><h3>Closest related material</h3><p>Related passages do not necessarily answer your question.</p>{message.answer.sources.slice(0,3).map(s=>citation(s.chunk_id,message.answer))}</div>}<details className="mode-note"><summary>Answer mode & limitations</summary><p>{message.answer.mode}</p>{message.answer.warnings.map((w,n)=><p key={n}>{w}</p>)}</details></div>{i===messages.length-1&&message.answer.claims.length>0&&<div className="actions"><span>KEEP LEARNING</span><button disabled={!!busy} onClick={()=>void ask('Explain that more simply','simple')}><Sparkles size={14}/> Explain simply</button><button disabled={!!busy} onClick={()=>void ask('Turn this into a 5-mark answer','exam')}>5-mark answer</button><button disabled={!!busy} onClick={()=>{setQuestion('Compare this with ');globalThis.document.getElementById('question')?.focus()}}>Compare</button><button disabled={!!busy} onClick={()=>void makeQuiz()}><Target size={14}/> Quiz me</button><button onClick={()=>void save()}><Bookmark size={14}/> Save</button></div>}</article>)}</div>}
    {quiz&&<section className="quiz-panel panel"><div className="panel-heading"><h2><Target size={18}/> Quick recall</h2><span className="type-tag">SOURCE-BASED CLOZE</span></div><p>{quiz.question}</p>{grade?<div className={'grade '+(grade.correct?'good':'weak')}><strong>{grade.correct?'Correct — keep it up.':'This topic needs another look.'}</strong><p>Expected: <b>{grade.expected}</b></p><p>{grade.evidence}</p><button className="text-link" onClick={()=>setPage('sprint')}>See your Exam Sprint <ArrowRight size={14}/></button></div>:<form onSubmit={gradeQuiz}><input aria-label="Quiz answer" value={quizInput} onChange={e=>setQuizInput(e.target.value)} placeholder="Type the missing word…" required/><button className="primary" disabled={!!busy||!quizInput.trim()}>Check answer <Check size={15}/></button></form>}</section>}</section><Evidence source={selected} onClose={()=>setSelected(null)}/></div>}
    {page==='materials'&&<><div className="materials-toolbar"><div><h2>Your source library</h2><p className="small-muted">Originals stay local. Re-index after adding files to your corpus folder.</p></div><div className="toolbar-buttons"><button className="secondary" disabled={!!busy} onClick={()=>void ingest()}><RotateCcw size={15}/> Re-index local corpus</button><label className="primary upload-button"><Upload size={15}/> Add material<input type="file" accept=".pdf,.ppt,.pptx,.md,.txt,.jpg,.jpeg,.png,.webp" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label></div></div><div className="material-grid">{docs.map(d=><article className="material-card panel" key={d.id}><div className="material-icon"><FileText size={26}/></div><span className="type-tag">{d.source_type==='handwritten'?'Handwritten':label(d.source_type)}</span><h3>{d.name.split('/').pop()}</h3><p>{d.units} {d.source_type==='pptx'?'slides':d.source_type==='markdown'||d.source_type==='text'?'sections':'pages'} · {d.chunks} indexed passages</p>{d.low_quality>0?<p className="quality-warning">{d.low_quality} passages need extraction review</p>:<p className="ready"><Check size={14}/> Ready to search</p>}<button className="text-link" onClick={()=>{setDocument(d.id);setPage('study')}}>Study this source <ArrowRight size={15}/></button></article>)}</div>{!docs.length&&<div className="panel empty-state"><FolderOpen size={36}/><h2>Your library is waiting.</h2><p>Add course files or re-index your local corpus to get started.</p></div>}<div className="privacy-note"><ShieldCheck size={20}/><div><h3>Private material belongs in your private corpus.</h3><p>Uploads are stored locally. The public demo corpus is synthetic and does not replace your real course material.</p></div></div></>}
    {page==='sprint'&&<><div className="sprint-stats"><div className="panel stat"><span>TOPICS TO REVISIT</span><strong>{sprint?.weak.length||0}</strong><p>Based on quiz attempts</p></div><div className="panel stat"><span>QUIZ RECALL</span><strong>{sprint?.quiz_correct||0}<small> / {sprint?.quiz_total||0}</small></strong><p>Correct responses / attempts</p></div><div className="panel stat"><span>SAVED FOR REVISION</span><strong>{sprint?.saved.length||0}</strong><p>Grounded study answers</p></div></div><div className="sprint-grid"><section className="panel"><div className="panel-heading"><h2><Target size={18}/> Your revision focus</h2></div>{sprint?.topics.length?sprint.topics.map(t=><div className="topic-row" key={t.topic}><div><h3>{t.topic}</h3><p>{t.total?`${t.correct} correct in ${t.total} attempts`:'Studied — not yet quizzed'}</p></div><span className={'topic-state '+t.status.toLowerCase()}>{label(t.status)}</span><button className="icon-button" title="Revisit topic" onClick={()=>void ask(t.topic)}><ArrowUpRight size={18}/></button></div>):<div className="empty-state"><Target size={32}/><h3>Make your first study move.</h3><p>Ask a question, try a quiz, and your revision focus will appear here.</p><button className="text-link" onClick={()=>setPage('study')}>Go to study workspace <ArrowRight size={15}/></button></div>}</section><section className="next-topic"><span className="eyebrow">A GOOD NEXT STEP</span><h2>{sprint?.recommended?.topic||'Start with a topic that feels uncertain.'}</h2><p>{sprint?.coverage_note||'Your study activity and quiz attempts will shape your next revision step.'}</p><button onClick={()=>sprint?.recommended?void ask(sprint.recommended.topic):setPage('study')}>Let’s work on it <ArrowRight size={16}/></button></section></div><section className="saved-section"><h2><Bookmark size={19}/> Saved evidence</h2>{sprint?.saved.length?sprint.saved.map((a,i)=><button className="saved-card panel" key={i} onClick={()=>{setSelected(a.sources[0]||null);setPage('study')}}><span>{a.resolved_question}</span><small>{a.claims.length} cited claims</small><ArrowUpRight size={18}/></button>):<p className="small-muted">Save a supported answer from the study workspace to keep it close.</p>}</section></>}
    <footer className="page-footer"><ShieldCheck size={13}/> Study from your material. Verify every answer. <span>Grounded Study Mode is always on.</span></footer>
  </main></div></div>
}
export default App
